apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: openshift-etcd-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 2000
  priorityLevelConfiguration:
    name: openshift-control-plane-operators
  rules:
  - resourceRules:
    - apiGroups:
      - apiGrousValue
      clusterScope: true
      namespaces:
      - openshift-etcd-operator
      resources:
      - resourcesValue
      verbs:
      - verbValue
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        namespace: etcd-operator
        name: system:serviceaccount:openshift-etcd-operator:etcd-operator
